especie<- c("gorrion","martin", "aguila", "colibri","gorrion", "martin","aguila", "colibri", "gorrion", "martin", "aguila", "colibri")
talla<- c(22,26,195,8,24,23,201,9,21,25,185,9)
data<- data.frame(especie,talla)
especie<- as.factor(especie)
gorrión<- filter(data,especie =="gorrion")
martín<- filter(data,especie=="martin")
águila<- filter(data,especie=="aguila")
colibrí<- filter(data,especie=="colibri")
media.gorrión<- mean(unique(gorrión$talla))
media.martín<- mean(unique(martín$talla))
media.águila<- mean (unique(águila$talla))
media.colibrí<- mean(unique(colibrí$talla))
medias<- c(media.gorrión,media.martín,media.águila,media.colibrí)
barplot(medias, names.arg = c("Gorrión","Martín", "Águila","Colibrí"), ylim=c(0,200))
